FROM node:16-alpine as build-step
WORKDIR /app
ENV PATH /app/node_modules/.bin:$PATH
COPY ./frontend/lms/package.json ./frontend/lms/package-lock.json ./
COPY ./frontend/lms/src ./src
COPY ./frontend/lms/public ./public
RUN yarn install
RUN yarn build

FROM nginx:stable-alpine
COPY --from=build-step /app/build /usr/share/nginx/html
